### ISSUE TITLE
Separate Pause logic from Replay logic and implement a better UI/representation for the pause state.

### ISSUE THREAD

**Issue by AkshayAgarwal007** [Vigneshsekar/Tux4ME#27]
The pause logic has been re-implemented using a pauseState variable that keep tracks of the current state (pause or not) We need to replace it with game.paused. The game can be paused simply by assigning game.paused a bool value of true. This is more efficient.

Moreover , the pause logic and the replay logic needs to be separated from each other. Also, a better representation(in terms of UI) of the pause state is required.

**Comment by AkshayAgarwal007** [comment]
This is similar to https://github.com/Vigneshsekar/Tux4ME/issues/1 . A documentation of your code would be useful to implement this. I'm half done but variables like gamephase and for what other conditional branches you are using the pauseState variable(and why?),if you can tell me that in brief, it would be very easy to fix this.

**Comment by Vigneshsekar** [comment]
Any conversation regarding this may be carried out under issue #1

**Comment by AkshayAgarwal007** [comment]
separating the pause and replay logic is quite different from using game.paused that phaser supports. This should be two different issues. I just referenced it to #1 .
