### ISSUE TITLE
Wrapping Tux4ME into a hybrid app.

### ISSUE THREAD

**Issue by AkshayAgarwal007** [Vigneshsekar/Tux4ME#31]
We should consider building a cross platform desktop app for Tux4ME using electron because that gives a better performance than an Apache Cordova+Crosswalk built hybrid app. Moreover we can test a Cordova/Crosswalk built app on a few devices ( categorizing them on the basis of specifications and picking one out of each category and test the performance of the app, since, emulators are not very good at this. So if doesn't wok fine we can try something like cocoon.js or Ionic. Issues with WebGL and compatibility of the crosswalk web view will always be a trouble while we are targeting older devices and this has to be dealt with.

**Comment by AkshayAgarwal007** [comment]
A Cordova build on Windows is looking pretty good. For mobile app the UI has to be made more responsive and touch interface needs to be added. I'm using the Intel XDK App Preview and the emulators that comes with Intel XDK for testing the performance out.

![screenshot 68](https://cloud.githubusercontent.com/assets/8170214/13902413/afd0b5b4-ee6c-11e5-80cb-b289f8b2ff04.png)
![screenshot 69](https://cloud.githubusercontent.com/assets/8170214/13902414/afd15d20-ee6c-11e5-9cce-ef133b7411aa.png)
![screenshot 70](https://cloud.githubusercontent.com/assets/8170214/13902416/afd3a29c-ee6c-11e5-969f-118cb36c05b0.png)
![screenshot 71](https://cloud.githubusercontent.com/assets/8170214/13902415/afd2267e-ee6c-11e5-9eac-714b22d70e40.png)
![screenshot 72](https://cloud.githubusercontent.com/assets/8170214/13902417/afdc0d6a-ee6c-11e5-8371-b478f06c3673.png)

**Comment by Vigneshsekar** [comment]
Again thanks for the testing and we appreciate your interest. All that you mentioned is in the ideas list and any GSoC'16 aspirant (if selected) may work them out in this summer. Please refer to the ideas list.

FYI - Touch inputs are already enabled. But the canvas is not responsive  as you mentioned and many contributors are coming up with very good ideas to bring Tux4ME to mobile.
