### ISSUE TITLE
Bug in "Click here to finish the game"  button

### ISSUE THREAD

**Issue by arun1128** [Vigneshsekar/Tux4ME#7]
When this button is clicked multiple times, "**Game over**" image also appears multiple times with it's active event listener. And we're unable to play the game further

**Comment by Vigneshsekar** [comment]
Thanks Arun. We'll fix the bug very soon. @karthikeyan5  has already started working on this issue.

**Comment by karthikeyan5** [comment]
You have a good eye for Bugs @arun1128.
I have been working on this issue in the weekend and managed to fix it.
Please try it out and give your feedback (hopefully @Vigneshsekar accepts the pull request by then).
Thanks @arun1128

**Comment by Vigneshsekar** [comment]
Thanks both of you. I am closing the issue.

**Comment by Vigneshsekar** [comment]
If the player looses all three lives, "Click here to finish the game" button must disappear and "Game Over " button must appear. 
In the latest pull request by @karthikeyan5, this was not made. So I will keep this issue open and will try to fix it soon.

**Comment by karthikeyan5** [comment]
@Vigneshsekar I hope the issue has been fixed.
if so, it would be a wonderful idea to close this issue. :)

**Comment by Vigneshsekar** [comment]
Thanks karthikeyan5
